# Generated by Django 4.2.8 on 2024-10-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verify",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="id_telegram",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телеграм ID"
            ),
        ),
    ]
