# Generated by Django 4.2.8 on 2024-10-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=200, verbose_name="Место привычки"),
                ),
                (
                    "time",
                    models.TimeField(
                        default=django.utils.timezone.now, verbose_name="Время привычки"
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=250, verbose_name="Действие привычки"),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Периодичность"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=120,
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cоздатель привычки",
                    ),
                ),
                (
                    "link_nice_habbit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habbit",
                        to="habbits.habbit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
